name: Flutter Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests with Coverage & JUnit Output
        run: |
          flutter test --machine > test_output.log
          cat test_output.log | jq -s -R -r 'split("\n") | map(select(length > 0)) | .[]' | tee test_output_pretty.log
          flutter test --reporter=expanded --coverage
        continue-on-error: true

      - name: Convert Test Results to JUnit (if needed)
        run: |
          dart pub global activate junitreport
          cat test_output.log | dart pub global run junitreport:machine > report.xml

      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: flutter-test-report
          path: report.xml
